In [2]:
import pandas as pd
import numpy as np

In [14]:
prices = np.array([100, 102, 100, 105, 103])

In [15]:
prices

array([100, 102, 100, 105, 103])

In [16]:
np.diff(prices)

array([ 2, -2,  5, -2])

In [19]:
prices[:-1]

array([100, 102, 100, 105])

In [12]:

np.diff(prices) / prices[:-1]

array([ 0.02      , -0.01960784,  0.05      , -0.01904762])

In [26]:
prices = pd.DataFrame(prices)
a = prices.pct_change()

In [28]:
(1+ a).cumprod()

0
0   NaN
1  1.02
2  1.00
3  1.05
4  1.03

In [31]:
a, 1+ a, (1+ a).cumprod()

(          0
 0       NaN
 1  0.020000
 2 -0.019608
 3  0.050000
 4 -0.019048,
           0
 0       NaN
 1  1.020000
 2  0.980392
 3  1.050000
 4  0.980952,
       0
 0   NaN
 1  1.02
 2  1.00
 3  1.05
 4  1.03)